[package]
name = "godot_rust_test"
version = "0.1.0"
authors = ["Vitaliy Alifanov <alifanov.vitalik@yandex.ru>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = "0.10.0"
# gdnative = { path = "../../godot-rust/gdnative" }
